/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppEpicsRouteRouteImport } from './routes/app/epics/route'
import { Route as AppEpicsIndexRouteImport } from './routes/app/epics/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEpicsRouteRoute = AppEpicsRouteRouteImport.update({
  id: '/app/epics',
  path: '/app/epics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEpicsIndexRoute = AppEpicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEpicsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/epics': typeof AppEpicsRouteRouteWithChildren
  '/app/epics/': typeof AppEpicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/epics': typeof AppEpicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/epics': typeof AppEpicsRouteRouteWithChildren
  '/app/epics/': typeof AppEpicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app/epics' | '/app/epics/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app/epics'
  id: '__root__' | '/' | '/app/epics' | '/app/epics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppEpicsRouteRoute: typeof AppEpicsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/epics': {
      id: '/app/epics'
      path: '/app/epics'
      fullPath: '/app/epics'
      preLoaderRoute: typeof AppEpicsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/epics/': {
      id: '/app/epics/'
      path: '/'
      fullPath: '/app/epics/'
      preLoaderRoute: typeof AppEpicsIndexRouteImport
      parentRoute: typeof AppEpicsRouteRoute
    }
  }
}

interface AppEpicsRouteRouteChildren {
  AppEpicsIndexRoute: typeof AppEpicsIndexRoute
}

const AppEpicsRouteRouteChildren: AppEpicsRouteRouteChildren = {
  AppEpicsIndexRoute: AppEpicsIndexRoute,
}

const AppEpicsRouteRouteWithChildren = AppEpicsRouteRoute._addFileChildren(
  AppEpicsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppEpicsRouteRoute: AppEpicsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
